# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-11T22:08:18+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class InstanceWithKey(BaseModel):
    instanceId: str | None = None
    secretKey: str | None = None


class Product(BaseModel):
    productId: str
    name: str
    categories: list[str] = Field(..., min_length=1)


class BulkSkippedProduct(BaseModel):
    productId: str
    reason: str


class ProductUpdate(BaseModel):
    name: str | None = None
    categories: list[str] | None = Field(None, min_length=1)


class Rating(BaseModel):
    userId: str
    productId: str
    score: float


class RatingKey(BaseModel):
    userId: str
    productId: str


class Recommendation(BaseModel):
    productId: str | None = None
    score: float | None = None


class Error(BaseModel):
    reason: str


class InstanceRegistration(BaseModel):
    catalog: list[Product]
    ratings: list[Rating]


class BulkProductResult(BaseModel):
    created: list[Product]
    skipped: list[BulkSkippedProduct]
